apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base

components:
  - ../../../../components/nginx

patches:
  - path: service-patch.yml
  - path: nginx-service-patch.yml
