apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  db_user: "testuser"
  db_password: "testpassword"
---
# Create this secret with:
# kubectl create secret generic app-secret \
#   --from-literal=db_user=your_username \
#   --from-literal=db_password=your_password
