apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: general-bs
provisioner: cinder.csi.openstack.org
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: General SSD
